### ISSUE TITLE
"Internal bag error" when 1000 Heavy Shot is only thing in shipping list

### ISSUE THREAD

**Issue by fusionpit** [Cormeer/PersonalShopper#1]
I added Heavy Shot x 1000 to my list.  Every time I open a vendor that sells Heavy Shot, it displays the error "Internal bag error" and nothing is purchased.

**Comment by Cormeer** [comment]
Hm, that is interesting. I will start looking into this right away. Thank
you for the bug report!

**Comment by Cormeer** [comment]
This was resolved in version 1.1. I simply forgot to update this issue.
